name: Trigger auto deployment for containerapps-agent-whatsapp

on:
  push:
    branches:
      [ main ]
    paths:
      - '**'

  workflow_dispatch:     

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONTAINERAPPSAGENTWHATSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSAGENTWHATSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSAGENTWHATSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: acragentewhatsappvladimir.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPSAGENTWHATSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSAGENTWHATSAPP_REGISTRY_PASSWORD }}
          containerAppName: containerapps-agent-whatsapp
          resourceGroup: rg-agent-whatsapp
          imageToBuild: acragentewhatsappvladimir.azurecr.io/bot-whatsapp:${{ github.sha }}
